# Generated by Django 5.1.15 on 2026-09-03 06:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('ai_base_url', models.CharField(blank=True, default='', max_length=256)),
                ('ai_api_key', models.CharField(blank=True, default='', max_length=256)),
                ('ai_model', models.CharField(blank=True, default='', max_length=64)),
                ('mastery_required', models.SmallIntegerField(default=2)),
                ('daily_new_limit', models.SmallIntegerField(default=20)),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_base_url', models.CharField(blank=True, default='', max_length=256)),
                ('ai_api_key', models.CharField(blank=True, default='', max_length=256)),
                ('ai_model', models.CharField(blank=True, default='', max_length=64)),
                ('mastery_required', models.SmallIntegerField(default=2)),
                ('daily_new_limit', models.SmallIntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户配置',
                'verbose_name_plural': '用户配置',
            },
        ),
    ]
