# Generated by Django 5.1.15 on 2026-09-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaperMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(db_index=True)),
                ('module', models.CharField(choices=[('writing', '图表作文'), ('translation', '段落翻译'), ('reading', '阅读理解(Part A)'), ('cloze', '完形填空'), ('newtype_b', '新题型 Part B(保留占位)')], db_index=True, max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=256)),
                ('has_ref_zh', models.BooleanField(default=False, help_text='有参考译文/参考答案')),
                ('has_chart', models.BooleanField(default=False, help_text='写作:有结构化图表配置;阅读:有题干+选项')),
                ('note', models.CharField(blank=True, default='', max_length=256)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '真题元数据',
                'verbose_name_plural': '真题元数据',
                'ordering': ('-year', 'module'),
                'unique_together': {('year', 'module')},
            },
        ),
    ]
