# Generated by Django 5.1.15 on 2026-09-03 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(db_index=True)),
                ('slice_id', models.CharField(help_text='如 s1/s2/s10, 对应 content/translation/<year>.json 的 slice.id', max_length=16)),
                ('source_text', models.TextField(blank=True, default='', help_text='冗余存一份原文,前端直接拿了做 Diff 展示')),
                ('user_translation', models.TextField()),
                ('ref_zh', models.TextField(blank=True, default='', help_text='提交时后端的参考译文快照(如果有)')),
                ('diff_report', models.JSONField(blank=True, default=dict, help_text='{equal:[{idx,text}],added:[{idx,text}],removed:[{idx,text}]}')),
                ('ai_feedback', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trans_attempts', to='accounts.device')),
            ],
            options={
                'verbose_name': '翻译提交记录',
                'verbose_name_plural': '翻译提交记录',
                'ordering': ('-created_at',),
            },
        ),
    ]
