# Generated by Django 5.1.15 on 2026-09-03 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(db_index=True, help_text='真题年份')),
                ('chart_info', models.TextField(blank=True, default='', help_text='传给 AI 的当前图表核心数据背景')),
                ('user_essay', models.TextField(help_text='考生提交作文原文')),
                ('total_score', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('s_data', models.DecimalField(decimal_places=1, default=0.0, help_text='数据完整度(满分4)', max_digits=4)),
                ('s_logic', models.DecimalField(decimal_places=1, default=0.0, help_text='归因论述逻辑(满分4)', max_digits=4)),
                ('s_vocab', models.DecimalField(decimal_places=1, default=0.0, help_text='词汇句式丰富度(满分4)', max_digits=4)),
                ('s_grammar', models.DecimalField(decimal_places=1, default=0.0, help_text='语法与拼写(满分3)', max_digits=4)),
                ('data_feedback', models.TextField(blank=True, default='')),
                ('logic_feedback', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('corrections', models.JSONField(blank=True, default=list)),
                ('ai_base_url', models.CharField(blank=True, default='', max_length=256)),
                ('ai_model', models.CharField(blank=True, default='', max_length=64)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='', help_text='AI 调用失败时留的错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '作文批改记录',
                'verbose_name_plural': '作文批改记录',
                'ordering': ('-created_at',),
            },
        ),
    ]
