# Generated by Django 5.1.15 on 2026-09-03 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.CharField(db_index=True, help_text='单词原型(还原成 lemma 后作为主键)', max_length=64, unique=True)),
                ('phonetic', models.CharField(blank=True, default='', max_length=128)),
                ('senses', models.JSONField(blank=True, default=list, help_text='[{"pos":"n","definition":"释义"}]')),
                ('collocations', models.JSONField(blank=True, default=list, help_text='常见搭配字符串数组')),
                ('cached_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '单词释义缓存',
                'verbose_name_plural': '单词释义缓存',
                'ordering': ('lemma',),
            },
        ),
        migrations.CreateModel(
            name='VocabCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_sentence', models.TextField(blank=True, default='')),
                ('source_path', models.CharField(blank=True, default='', help_text='translation/2023 / writing/2021 / reading/2024-p1 ...', max_length=128)),
                ('due', models.DateTimeField(db_index=True, help_text='下次复习到期时间')),
                ('stability', models.FloatField(default=0.0)),
                ('difficulty', models.FloatField(default=0.0)),
                ('elapsed_days', models.IntegerField(default=0)),
                ('scheduled_days', models.IntegerField(default=0)),
                ('reps', models.IntegerField(default=0)),
                ('lapses', models.IntegerField(default=0)),
                ('state', models.SmallIntegerField(choices=[(0, '新词'), (1, '学习中'), (2, '复习中'), (3, '再学习')], default=0)),
                ('last_review', models.DateTimeField(blank=True, null=True)),
                ('consecutive_correct', models.SmallIntegerField(default=0)),
                ('mastered', models.BooleanField(db_index=True, default=False, help_text='业务标记,掌握后不进 due 队列')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_cards', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='vocab.word')),
            ],
            options={
                'verbose_name': '生词卡',
                'verbose_name_plural': '生词卡',
                'ordering': ('due',),
                'indexes': [models.Index(fields=['user', 'due', 'mastered'], name='vocab_vocab_user_id_c104f4_idx')],
                'unique_together': {('user', 'word', 'source_path')},
            },
        ),
    ]
